### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by Arex360** [Metater/MetaVoiceChat#1]
![Capture](https://github.com/user-attachments/assets/87dfae45-9b8a-4b94-8e65-5c95c6c0cdca)

This is my configuration and I can't listen to anything, even I tried echo enabled. I am using Mirror 93.0.1. I also have provided the Mirror Provider inside the gameobject (along with network identity)

**Comment by Arex360** [comment]
thank you @Metater for you support in discord, problem is solved. For those who are experiencing the same issue, make sure you don't use it in scene (as I considered it like Game Manager instance) , rather use it with your Network Player 

![Capture](https://github.com/user-attachments/assets/ea4082ea-5a5c-499c-be3f-46ded6627c01)


It should look like this

**Comment by Metater** [comment]
It is not required to separate "input" and "output" btw. They can be placed under "voice".

When you are using a player model, just place the "voice_output" game object where your player's mouth is in the world.
